### ISSUE TITLE
Simple Magnets [1.0.4] 1.16.2 Crash Report

### ISSUE THREAD

**Issue by Mikeliro** [SuperMartijn642/SimpleMagnets#2]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 13/08/20 22:33
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.client.gui.FontRenderer.func_238422_b_(Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/util/text/ITextProperties;FFI)I
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.drawCenteredString(MagnetContainerScreen.java:138) ~[?:?] {re:classloading}
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.func_230450_a_(MagnetContainerScreen.java:118) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.func_230430_a_(MagnetContainerScreen.java:71) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:585) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.2.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/22040992.call(Unknown Source) [forge-1.16.2-33.0.2.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.drawCenteredString(MagnetContainerScreen.java:138)
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.func_230450_a_(MagnetContainerScreen.java:118)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:88)
	at com.supermartijn642.simplemagnets.gui.MagnetContainerScreen.func_230430_a_(MagnetContainerScreen.java:71)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)

-- Screen render details --
Details:
	Screen name: com.supermartijn642.simplemagnets.gui.MagnetContainerScreen
	Mouse location: Scaled: (341, 176). Absolute: (683.000000, 352.000000)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Mikeliro'/260, l='ClientLevel', x=-152.71, y=64.00, z=-118.43]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,64,-111), Chunk: (at 0,4,1 in -8,-7; contains blocks -128,0,-112 to -113,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 11669 game time, 11669 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1975)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:601)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/22040992.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3146981232 bytes (3001 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.2.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.2
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.2-client.jar Minecraft {minecraft@1.16.2 DONE}
		EN - Factory [1.1.1].jar Factory Mod {factory@1.16.2-1.1.1 DONE}
		NO - Lenient Creepers [1.0.1].jar LenientCreepers {lenientcreepers@v1.0.1 DONE}
		PT - Wormhole [1.0.7].jar Wormhole (Portals) {wormhole@1.0.7 DONE}
		PT - Simple Magnets [1.0.4].jar Simple Magnets {simplemagnets@1.0.4 DONE}
		PT - Jei [7.1.0.11].jar Just Enough Items {jei@7.1.0.11 DONE}
		NO - Ceiling Torch [1.8].jar Ceiling Torch {ceilingtorch@v1.8 DONE}
		EN - Falling Tree [2.2.1].jar Falling Tree {falling_tree@2.2.1 DONE}
		PT - Enchant With Mob [1.5.0].jar Enchant With Mob {enchantwithmob@1.16.2-1.5.0 DONE}
		forge-1.16.2-33.0.2-universal.jar Forge {forge@33.0.2 DONE}
		PT - Easy Villagers[1.0.2].jar Easy Villagers {easy_villagers@1.16.2-1.0.2 DONE}
		NO - Reap [1.0.1].jar Reap Mod {reap@1.16.2-1.0.1 DONE}
		NO - Overpowered Mending [2.2.1].jar Overpowered Mending {overpowered_mending@2.2.1 DONE}
		EN - Air Hop [1.3.1] [EN].jar Air Hop {airhop@1.3.1 DONE}
		PT - Corpse [1.0.2].jar Corpse {corpse@1.16.2-1.0.2 DONE}
		EN - Fake Blocks [1.0.1].jar Fake Blocks {fakeblocks@1.16.2-1.0.1 DONE}
	Launched Version: 1.16.2-forge-33.0.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 430/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, mod_resources (incompatible), file/Mikeliro [3D] 1.16.2.zip, file/Mikeliro [3D] [Items] 1.16.2.zip, file/Mikeliro [3D] [MOD's] [Items] 1.16.2.zip, file/Mikeliro [MOD's] 1.16.2.zip
	Current Language: Português (Brasil)
	CPU: 4x Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz

**Comment by SuperMartijn642** [comment]
I fixed now in version 1.0.4a.

Thanks for the report!
